apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 32000
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      nodePort: 32001
      targetPort: 443
 
